// Word pairs: [normalWord, imposterWord, category]
const WORD_PAIRS = [
  // Animals
  ["Cat", "Tiger", "Animals"],
  ["Dog", "Wolf", "Animals"],
  ["Horse", "Zebra", "Animals"],
  ["Dolphin", "Shark", "Animals"],
  ["Eagle", "Hawk", "Animals"],
  ["Lion", "Cheetah", "Animals"],
  ["Elephant", "Rhinoceros", "Animals"],
  ["Penguin", "Seal", "Animals"],
  ["Rabbit", "Hare", "Animals"],
  ["Crow", "Raven", "Animals"],
  ["Frog", "Toad", "Animals"],
  ["Butterfly", "Moth", "Animals"],
  ["Crocodile", "Alligator", "Animals"],
  ["Gorilla", "Chimpanzee", "Animals"],
  ["Camel", "Llama", "Animals"],
  ["Kangaroo", "Wallaby", "Animals"],
  ["Bear", "Panda", "Animals"],
  ["Snake", "Lizard", "Animals"],
  ["Spider", "Scorpion", "Animals"],
  ["Owl", "Parrot", "Animals"],
  ["Whale", "Shark", "Animals"],

  // Food
  ["Pizza", "Burger", "Food"],
  ["Apple", "Mango", "Food"],
  ["Coffee", "Tea", "Food"],
  ["Sushi", "Ramen", "Food"],
  ["Cake", "Pie", "Food"],
  ["Bread", "Croissant", "Food"],
  ["Tacos", "Burritos", "Food"],
  ["Steak", "Pork Chop", "Food"],
  ["Ice Cream", "Gelato", "Food"],
  ["Pasta", "Risotto", "Food"],
  ["Pancakes", "Waffles", "Food"],
  ["Chocolate", "Caramel", "Food"],
  ["Salad", "Coleslaw", "Food"],
  ["Soup", "Stew", "Food"],
  ["Donut", "Bagel", "Food"],
  ["Sandwich", "Wrap", "Food"],
  ["Cheese", "Butter", "Food"],
  ["Popcorn", "Chips", "Food"],
  ["Grapes", "Berries", "Food"],

  // Places
  ["Beach", "Desert", "Places"],
  ["Mountain", "Volcano", "Places"],
  ["Forest", "Jungle", "Places"],
  ["City", "Town", "Places"],
  ["Library", "Bookstore", "Places"],
  ["Hospital", "Clinic", "Places"],
  ["Stadium", "Arena", "Places"],
  ["Museum", "Gallery", "Places"],
  ["Airport", "Train Station", "Places"],
  ["Hotel", "Hostel", "Places"],
  ["Park", "Garden", "Places"],
  ["School", "University", "Places"],
  ["Church", "Temple", "Places"],
  ["Prison", "Dungeon", "Places"],
  ["Casino", "Arcade", "Places"],
  ["Restaurant", "Cafe", "Places"],
  ["Cinema", "Theater", "Places"],
  ["Mall", "Market", "Places"],

  // Objects & Everyday Items
  ["Guitar", "Violin", "Objects"],
  ["Sword", "Dagger", "Objects"],
  ["Crown", "Tiara", "Objects"],
  ["Lantern", "Candle", "Objects"],
  ["Compass", "Map", "Objects"],
  ["Telescope", "Microscope", "Objects"],
  ["Clock", "Sundial", "Objects"],
  ["Hammer", "Wrench", "Objects"],
  ["Paintbrush", "Pencil", "Objects"],
  ["Umbrella", "Raincoat", "Objects"],
  ["Backpack", "Suitcase", "Objects"],
  ["Torch", "Flashlight", "Objects"],
  ["Mirror", "Window", "Objects"],
  ["Ladder", "Staircase", "Objects"],
  ["Rope", "Chain", "Objects"],
  ["Glasses", "Contacts", "Objects"],
  ["Wallet", "Purse", "Objects"],
  ["Shoes", "Boots", "Objects"],
  ["Watch", "Bracelet", "Objects"],

  // Sports & Entertainment
  ["Movie", "TV Show", "Entertainment"],
  ["Chess", "Checkers", "Entertainment"],
  ["Poker", "Blackjack", "Entertainment"],
  ["Soccer", "Rugby", "Sports"],
  ["Basketball", "Volleyball", "Sports"],
  ["Swimming", "Diving", "Sports"],
  ["Bowling", "Billiards", "Sports"],
  ["Skiing", "Snowboarding", "Sports"],
  ["Painting", "Sculpting", "Entertainment"],
  ["Dancing", "Gymnastics", "Entertainment"],
  ["Hiking", "Camping", "Entertainment"],
  ["Fishing", "Hunting", "Entertainment"],
  ["Boxing", "Wrestling", "Sports"],
  ["Tennis", "Badminton", "Sports"],
  ["Photography", "Videography", "Entertainment"],
  ["Cricket", "Baseball", "Sports"],
  ["Golf", "Polo", "Sports"],

  // Nature
  ["Rain", "Snow", "Nature"],
  ["Thunder", "Lightning", "Nature"],
  ["River", "Lake", "Nature"],
  ["Cave", "Tunnel", "Nature"],
  ["Earthquake", "Tsunami", "Nature"],
  ["Rainbow", "Aurora", "Nature"],
  ["Tornado", "Hurricane", "Nature"],
  ["Glacier", "Iceberg", "Nature"],
  ["Swamp", "Marsh", "Nature"],
  ["Cliff", "Canyon", "Nature"],

  // Science & Tech
  ["Robot", "Android", "Tech"],
  ["Rocket", "Satellite", "Tech"],
  ["Laser", "Plasma", "Tech"],
  ["Computer", "Tablet", "Tech"],
  ["Virus", "Bacteria", "Science"],
  ["Atom", "Molecule", "Science"],
  ["Black Hole", "Nebula", "Science"],
  ["DNA", "RNA", "Science"],
  ["Battery", "Generator", "Tech"],
  ["Magnet", "Electromagnet", "Science"],
  ["Smartphone", "Telephone", "Tech"],
  ["Laptop", "Desktop", "Tech"],
  ["Headphones", "Earbuds", "Tech"],
  ["Keyboard", "Mouse", "Tech"],
  ["Internet", "WiFi", "Tech"],

  // Mythology & Fantasy
  ["Dragon", "Griffin", "Fantasy"],
  ["Wizard", "Witch", "Fantasy"],
  ["Vampire", "Werewolf", "Fantasy"],
  ["Ghost", "Demon", "Fantasy"],
  ["Fairy", "Pixie", "Fantasy"],
  ["Giant", "Troll", "Fantasy"],
  ["Phoenix", "Dragon", "Fantasy"],
  ["Mermaid", "Siren", "Fantasy"],
  ["Knight", "Paladin", "Fantasy"],
  ["Elf", "Dwarf", "Fantasy"],

  // Famous Personalities & Professions
  ["Actor", "Director", "Professions"],
  ["Cricketer", "Footballer", "Professions"],
  ["Singer", "Rapper", "Professions"],
  ["Doctor", "Nurse", "Professions"],
  ["Pilot", "Astronaut", "Professions"],
  ["Chef", "Baker", "Professions"],
  ["Teacher", "Professor", "Professions"],
  ["Police", "Detective", "Professions"],
  ["Magician", "Clown", "Professions"],
  ["Scientist", "Engineer", "Professions"],
  ["Tom Cruise", "Brad Pitt", "Actors"],
  ["Leonardo DiCaprio", "Johnny Depp", "Actors"],
  ["Virat Kohli", "MS Dhoni", "Cricketers"],
  ["Sachin Tendulkar", "Brian Lara", "Cricketers"],
  ["Cristiano Ronaldo", "Lionel Messi", "Athletes"],
  ["Taylor Swift", "Selena Gomez", "Singers"],
  ["Iron Man", "Batman", "Superheroes"],
  ["Spider-Man", "Superman", "Superheroes"],

  // Cars & Vehicles
  ["Car", "Truck", "Vehicles"],
  ["Motorcycle", "Bicycle", "Vehicles"],
  ["Helicopter", "Airplane", "Vehicles"],
  ["Boat", "Ship", "Vehicles"],
  ["Submarine", "Torpedo", "Vehicles"],
  ["Ferrari", "Lamborghini", "Cars"],
  ["BMW", "Mercedes", "Cars"],
  ["Tesla", "Mustang", "Cars"],
  ["Jeep", "SUV", "Cars"],
  ["Train", "Tram", "Vehicles"],
  ["Bus", "Van", "Vehicles"]
];

module.exports = WORD_PAIRS;
